### ISSUE TITLE
package.xml format 3 with condition doesn't work properly.

### ISSUE THREAD

**Issue by obi-t4** [colcon/colcon-bundle#169]
colcon bundle with package.xml format 3 which contains `condition` like

https://github.com/KIT-MRT/mrt_cmake_modules/blob/ce7c854c48cb458cf55a238fcce4821396b695f1/package.xml#L16

does not work properly, as follows:
```python
--- stderr: mrt_cmake_modules                      
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/colcon_ros_bundle/task/ros_bundle.py", line 66, in bundle
    package_name = package_name_list[0]
IndexError: list index out of range
---
```

**Comment by obi-t4** [comment]
PR https://github.com/colcon/colcon-ros-bundle/pull/39 fixes this issue.

**Comment by thomas-moulard** [comment]
Thank you for the contribution, I think this should solve this ticket, feel free to re-open the issue if any additional work is needed.
