### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name'.

### ISSUE THREAD

**Issue by cheng-kevin** [colcon/colcon-bundle#222]
I am running into a colcon bundling error when it attempts to bundle gazebo_dev package from https://github.com/aws-ros-dev/gazebo_ros_pkgs/commit/25b295f47b7e0ac9807f92b4516784bc6c0bf4e8.  See error below:

```
root@uefee1b00be3a55:/aws-robomaker-sample-application-helloworld/simulation_ws# colcon build
Starting >>> gazebo_dev
Starting >>> gazebo_msgs
Finished <<< gazebo_dev [0.59s]                                                       
Finished <<< gazebo_msgs [29.8s]                       
Starting >>> gazebo_ros
[Processing: gazebo_ros]                                 
Finished <<< gazebo_ros [54.9s]                            
Starting >>> gazebo_plugins
[Processing: gazebo_plugins]                                  
[Processing: gazebo_plugins]                                      
[Processing: gazebo_plugins]                                       
Finished <<< gazebo_plugins [1min 52s]                              
Starting >>> gazebo_ros_pkgs
Starting >>> hello_world_simulation
Starting >>> turtlebot3_description_reduced_mesh
Finished <<< gazebo_ros_pkgs [0.62s]                                                                                                                           
Finished <<< hello_world_simulation [0.63s]
Finished <<< turtlebot3_description_reduced_mesh [1.91s]                      
Summary: 7 packages finished [3min 19s]
root@uefee1b00be3a55:/aws-robomaker-sample-application-helloworld/simulation_ws# colcon bundle
Bundling workspace...
Reading package lists... Done
Building dependency tree... Done
Checking if dependency tarball exists...
Starting >>> gazebo_dev    
loading view [*default*] with rospkg loader
--- stderr: gazebo_dev                         
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/colcon_ros_bundle/task/ros_bundle.py", line 30, in bundle
    if dependency.name in self.context.dependencies:
AttributeError: 'str' object has no attribute 'name'
---
Failed   <<< gazebo_dev	[ Exited with code 1 ]
Starting >>> gazebo_msgs
loading view [*default*] with rospkg loader                
Finished <<< gazebo_msgs [0.15s]                           
Summary: 1 package finished [1min 34s]
  1 package failed: gazebo_dev
  1 package had stderr output: gazebo_dev
  5 packages not processed
Creating bundle archive V2...
[97.766s] ERROR:colcon:colcon bundle: [Errno 2] No such file or directory: '/aws-robomaker-sample-application-helloworld/simulation_ws/bundle/cache/bundle_staging/setup.sh'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/colcon_core/command.py", line 505, in verb_main
    rc = context.args.main(context=context)
  File "/usr/local/lib/python3.8/dist-packages/colcon_bundle/verb/bundle.py", line 141, in main
    generate_archive_v2(self._path_contex,
  File "/usr/local/lib/python3.8/dist-packages/colcon_bundle/verb/_archive_generators.py", line 110, in generate_archive_v2
    create_dependencies_overlay(path_context.dependencies_staging_path(),
  File "/usr/local/lib/python3.8/dist-packages/colcon_bundle/verb/_overlay_utilities.py", line 78, in create_dependencies_overlay
    _render_template(
  File "/usr/local/lib/python3.8/dist-packages/colcon_bundle/verb/_overlay_utilities.py", line 136, in _render_template
    with script_dest.open('w') as file:
  File "/usr/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/aws-robomaker-sample-application-helloworld/simulation_ws/bundle/cache/bundle_staging/setup.sh'
```

Environment: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-latest
colcon-bundle version: 0.1.3
colcon-ros-bundle version 0.1.0

**Comment by murphm8** [comment]
This is the original `colcon-core` update which added the dependency object instead of just a string: https://github.com/colcon/colcon-core/commit/97bca644723292c163609c43ec6c520cd01f0968

The question here is where is this dependency coming from as that package appears to not be using the dependency object.

**Comment by murphm8** [comment]
This code should support the dependency objects being a string for backwards compatibility. We support it as a string somewhere else.

**Comment by murphm8** [comment]
It appears that whatever is adding metadata from this `*.pkg` file may not be using the `PackageDescriptor` type.

https://github.com/ros-simulation/gazebo_ros_pkgs/blob/foxy/gazebo_dev/colcon.pkg

**Comment by murphm8** [comment]
`.pkg` files are parsed here: https://github.com/colcon/colcon-metadata/blob/bb2c96e302689eee29c509c9f5619ed85ff55d42/colcon_metadata/metadata/colcon_pkg.py#L19
